### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by GordenGao1** [JeffSackmann/tennis_MatchChartingProject#12]
Hi! I'm interested in citing you data in my paper. Could you please provide the citation you'd like to be used? Thanks!

**Comment by JeffSackmann** [comment]
sorry, this is probably too late to be useful.

but if someone stumbles on this later, here's a stackexchange answer that offers a good template. there doesn't appear to be a standard, though there are standards for some journals.
https://academia.stackexchange.com/a/14015
