### ISSUE TITLE
Can't download files

### ISSUE THREAD

**Issue by lwstep** [JeffSackmann/tennis_MatchChartingProject#13]
Hello, I previously was able to download the charting-m-matches.csv file but now I seem to be unable to download this file or the charting-w-matches file. The points files don't seem to have this issue and still have a download button. Please let me know if there's a way to download these files. Thanks!

**Comment by JeffSackmann** [comment]
not sure how you were downloading before. You can click 'raw' and then save (ctrl-s or whatever) that way.
