### ISSUE TITLE
Sao Paulo is misspelled Sao Paolo

### ISSUE THREAD

**Issue by TennisVisuals** [JeffSackmann/tennis_MatchChartingProject#4]
20160226-M-Sao_Paolo-R16-Inigo_Cervantes_Huegun-Federico_Delbonis,Inigo Cervantes Huegun,Federico Delbonis,R,L,M,20160226,Sao Paolo,R16,,,Clay,,3,1,jeffsackmann

**Comment by JeffSackmann** [comment]
fixed
