### ISSUE TITLE
MCP Spreadsheet 1.5 misinterprets 4;d

### ISSUE THREAD

**Issue by TennisVisuals** [JeffSackmann/tennis_MatchChartingProject#5]
I believe it should be a wide serve (net cord) out long.  When this is entered as a first serve, the spreadsheet assigns a point to the receiver and ignores a coded second serve.

removing the ';' net cord indicator causes the second serve to be considered

I have encountered other instances where the point *result* is correct, but because of a ';' net cord present in a first serve, many other statistics are thrown off, such as first/second points won and counts for winners/errors & etc.

**Comment by JeffSackmann** [comment]
the semi-colon is only used within the rally.

a serve that hits the net cord and goes out is coded as 'n', e.g. 4n.
