### ISSUE TITLE
Not all matches are Present

### ISSUE THREAD

**Issue by jgollub1** [JeffSackmann/tennis_MatchChartingProject#9]
Currently, the match charting website lists over 2900 charted matches. I only see about 1800 men's matches referenced in both the charting-m-matches.csv and charting-m-points.csv file. I looked up a few players and was able to find all shot-level data available on the website, just not in the csv files. Is there a reason not all matches are present on github? Thanks

**Comment by JeffSackmann** [comment]
This is by design. I'll no longer make all matches available here.

**Comment by jgollub1** [comment]
For whom will the entire dataset be available? Volunteers who chart sufficient matches? Paying subscribers? Researchers?
